# SConstruct
#
# Copyright (c) 2015 Kevin Laeufer <kevin.laeufer@rwth-aachen.de>


import os

awap_root = os.path.join('..', '..')

env = Environment(toolpath = [os.path.join(awap_root, 'scons')], tools = ['awap'])

env.AppendUnique(AWAP_AGENT_PATH = os.path.join(awap_root, 'examples', 'agents'))
env.AppendUnique(AWAP_COMMUNICATION_PATH = os.path.join(awap_root, 'examples', 'communication'))
env.LoadAwapConfiguration(os.path.join(awap_root, 'examples', 'configuration', 'simple.xml'))

env.Architecture("amd64")
lib = SConscript(['SConscript'], exports = 'env')

env.Alias("generate", "libcommon.generate")

lib_size = env.ShowSize(lib)

env.Default(lib_size)
