# SConscript
#
# Copyright (c) 2015 Kevin Laeufer <kevin.laeufer@rwth-aachen.de>


Import('env')

base_lib = SConscript([env['OFT_ROOT'] + '/lib/base/SConscript'], exports = 'env')

common = env.OstfriesenteeLibrary('common', ['java'], OFT_LIBS=['base'])

Return('common')
