# SConstruct
# -*- coding: utf-8 -*-
#
# Copyright (c) 2015 Kevin Laeufer <kevin.laeufer@rwth-aachen.de>
#
# This file is part of awap.
#
#

import os

# root path of the awap repo
path_awap_root = os.path.abspath('../..')
# path to awap scons tools
path_awap_scons = os.path.join(path_awap_root, 'scons')


# create the scons environment which contains the custom awap build tools
env = Environment(toolpath = [path_awap_scons], tools = ['awap'])
# tell awap where to look for agents
env.AppendUnique(AWAP_AGENT_PATH = '../agents')
# tell awap where to look for communication modules
env.AppendUnique(AWAP_COMMUNICATION_PATH = '../communication')

# build awap configuration
env.Awap(configuration = 'configuration.xml')

# print the size of the resulting temperature sensor
env.Default(['awap-common.size', 'TemperatureSensor.size', 'SimpleTemperatureSubscriber.size'])
